version: "3.1"
services:
    php:
      build: 
        context: .
        dockerfile: Dockerfile
      container_name: php-iot
      volumes:
        - ./:/var/www/html
        - ./:/app

    webserver:
      image: nginx:1.17.10
      container_name: nginx-webserver-iot
      links:
        - php:fpm
      environment:
        - FPM_HOST=fpm
        - FPM_PORT=9000
      volumes:
        - ./:/var/www/html
        - ./docker/nginx_conf:/etc/nginx/conf.d/
      ports:
       - "8080:80"
